FROM python:3.11

WORKDIR /app

ENV REDIS_URL = $REDIS_URL

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "celery_worker", "worker", "--loglevel=info"]